language: php
php:
  - '7.0'
  - '7.1'
  
before_script:
  - cp .env.travis .env
  - touch database/database.sqlite
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  
script: vendor/bin/phpunit
